// Ejemplo DISTRIB+ de Gestión del Conocimiento — UNA sola fuente. Amplía el MISMO caso (Regla #6 de CLAUDE.md): cada lección nace de un hecho que ya cuenta el resto del caso al corte (2026-11-03): el hallazgo
// geotécnico R-03 (materializado) y su orden de cambio OC-001, la no conformidad NC-01 de las estructuras (R-08), la licencia municipal (R-01), la mesa vecinal (R-07), la convocatoria anticipada del
// acero (PR-01, R-02), el criterio de aceptación del diccionario de la EDT y los 106 días de Acabados (4.4). Los responsables son puestos del OBS. Ninguna lección se transfirió todavía: el proyecto
// sigue en ejecución y la transferencia es del cierre. tests/unit/knowledge.test.ts lo verifica contra el Registro de Riesgos del caso.
import { SAMPLE_OBS_ROLES, SAMPLE_CASE_LEAVES } from "./case-distribplus";
import { normalizeLesson, type KFacts, type KnowledgeData, type Lesson } from "./knowledge";
import { buildSampleRisks } from "./risk-sample";

export const SAMPLE_KNOWLEDGE_AS_OF = "2026-11-03";
export const sampleKnowledgeFacts = (): KFacts => {
  const risks = buildSampleRisks((code) => "w-" + code);
  return { materialized: risks.filter((r) => r.status === "materializado").map((r) => ({ code: r.code, title: r.title })), riskCodes: risks.map((r) => r.code),
    leaves: SAMPLE_CASE_LEAVES.map((l) => ({ id: "w-" + l.code, code: l.code, name: l.name })), roles: SAMPLE_OBS_ROLES.slice() };
};
// código · fecha · tipo · categoría · paquete · riesgo · situación · lección · recomendación · responsable · destinatarios · estado
type Row = [string, string, string, string, string, string, string, string, string, string, string, string];
const ROWS: Row[] = [
  ["LL-01", "2026-07-15", "buena_practica", "Alcance", "1.2", "", "El criterio de aceptación de cada paquete se escribió en el diccionario de la EDT antes de armar los controles de calidad.", "Tener el criterio de aceptación en la EDT permitió planificar cada control de calidad sin volver a preguntar qué significa «conforme».", "En todo proyecto, redactar el criterio de aceptación de cada paquete en la EDT antes de planificar la calidad y las adquisiciones.", "Jefe de Ingeniería", "Oficina de proyectos", "validada"],
  ["LL-02", "2026-08-06", "buena_practica", "Adquisiciones", "3.1", "R-02", "La fabricación de las estructuras metálicas es el paquete de mayor plazo y de mayor exposición al precio del acero.", "Convocar primero la compra crítica, con un contrato de ajuste económico, evitó que el alza del acero cayera entera sobre el proyecto.", "Calcular para cada compra la fecha límite de convocatoria contra el cronograma y lanzar antes la de mayor plazo y volatilidad de precio.", "Jefe de Logística", "Oficina de proyectos", "validada"],
  ["LL-03", "2026-08-27", "oportunidad", "Cronograma", "1.3", "", "Los informes de seguimiento (1.3) figuraban como un paquete de duración y aparecían como paquete demasiado largo en la calidad de la EDT.", "El seguimiento es esfuerzo continuo: medirlo por duración lo distorsiona.", "Declarar como esfuerzo continuo (LOE) los paquetes de gestión al armar el diccionario de la EDT.", "Director de Proyecto", "Oficina de proyectos", "validada"],
  ["LL-04", "2026-09-02", "problema", "Riesgos", "4.2", "R-03", "En la excavación de las zapatas apareció un suelo con menor capacidad portante que la del estudio: se aprobó el refuerzo de cimentación OC-001 (180.000) con cargo a la contingencia.", "Las calicatas del estudio de suelos no cubrieron el punto de mayor carga; el riesgo estaba identificado pero sin respuesta específica.", "Exigir una densidad mínima de calicatas por área de cimentación y reservar una contingencia geotécnica propia cuando el estudio es limitado.", "Jefe de Ingeniería", "Oficina de proyectos y Comité de Control de Cambios", "validada"],
  ["LL-05", "2026-09-30", "problema", "Cronograma", "4.4", "R-09", "Acabados y cerramientos (4.4) resultó con 106 días de duración porque sus tres actividades van en serie.", "Un paquete con actividades en serie es largo y difícil de controlar con avance real.", "Descomponer el paquete por zonas o frentes para que puedan avanzar en paralelo antes de fijar la línea base.", "Residente de Obra", "", "validada"],
  ["LL-06", "2026-10-15", "buena_practica", "Comunicaciones", "4.1", "R-07", "Se abrió la mesa de diálogo con la comunidad de Lurín un mes antes del movimiento de tierras.", "Explicar el plan de tráfico y ruido antes de empezar redujo la oposición y dio un canal para los reclamos.", "Abrir el canal con los vecinos antes del primer movimiento en obra y llevar un libro de reclamos con respuesta en plazo.", "Residente de Obra", "Oficina de proyectos", "validada"],
  ["LL-07", "2026-10-20", "problema", "Calidad", "3.1", "R-08", "Al recibir el lote 2 de estructuras, tres piezas tenían soldadura fuera de tolerancia y el certificado de calidad estaba incompleto (NC-01).", "Inspeccionar solo a la recepción en obra detecta el defecto tarde: el reproceso ocurre con la pieza ya despachada.", "Inspeccionar en fábrica antes del embarque, con protocolo de soldadura y certificados por lote como requisito de despacho.", "Control de Calidad", "", "capturada"],
  ["LL-08", "2026-10-27", "buena_practica", "Interesados", "2.4", "R-01", "La municipalidad envió por escrito observaciones al expediente de la licencia cuando el trámite ya estaba avanzado.", "Las reuniones técnicas semanales con la autoridad adelantaron la subsanación (presentada el 2/11) sin frenar el resto del cronograma.", "Pedir reunión técnica semanal con la autoridad desde el ingreso del expediente y registrar cada observación con su fecha.", "Asesoría Legal", "", "capturada"]
];
export function buildSampleKnowledge(resolveLeaf: (code: string) => string = (c) => "w-" + c): KnowledgeData {
  const lessons: Lesson[] = ROWS.map(([code, date, kind, category, wbs, riskCode, situation, lesson, recommendation, owner, audience, status], i) => normalizeLesson({ id: "ll" + (i + 1), code, date, kind, category, wbsId: resolveLeaf(wbs), riskCode, situation, lesson, recommendation, owner, audience, status }, "ll" + (i + 1)));
  return { lessons, asOf: SAMPLE_KNOWLEDGE_AS_OF, idCounter: lessons.length + 1 };
}
